#docker compose 파일
version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      #rds에서 설정한 end-point
      SPRING_DATASOURCE_URL: jdbc:mysql://rds-endpoint:3306/your-database-name
      SPRING_DATASOURCE_USERNAME: database-username
      SPRING_DATASOURCE_PASSWORD: database-password
    networks:
      - webnet

networks:
  webnet:
